name: Release Windows (PupNet)

on:
  workflow_dispatch:

env:
  PupNetVersion: "1.6.0"
  ProjectDir: "src/AvaloniaExample"
  ProjectName: "AvaloniaExample"
  SigningCertificate: GitHubActionsWorkflow.pfx

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Print debug info
        run: dotnet --info

      - name: Get PupNet
        run: dotnet tool install -g KuiperZone.PupNet --version ${{ env.PupNetVersion }}

      - name: Decode PFX
        shell: pwsh
        run: |
          $certBytes = [System.Convert]::FromBase64String("${{ secrets.PFX_BASE64 }}")
          $certPath = Join-Path -Path $env:ProjectDir -ChildPath $env:SigningCertificate
          [IO.File]::WriteAllBytes("$certPath", $certBytes)

      - name: Create Setup
        working-directory: ${{ env.ProjectDir }}
        run: pupnet -y -k Setup -p DefineConstants=INSTALLATION_METHOD_INNO_SETUP
        env:
          SignTool: signtool.exe
          SigningCertificatePassword: ${{ secrets.PFX_KEY }}

      - name: Remove PFX
        shell: pwsh
        run: |
          $certPath = Join-Path -Path $env:ProjectDir -ChildPath $env:SigningCertificate
          Remove-Item -Path $certPath

      - name: Create Archive
        working-directory: ${{ env.ProjectDir }}
        run: pupnet -y -k zip -p DefineConstants=INSTALLATION_METHOD_ARCHIVE

      - name: Upload Archive
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ProjectName }}-Windows-Archive
          path: ${{ env.ProjectDir}}/Deploy/OUT/*.zip
          if-no-files-found: error
          retention-days: 1

      - name: Upload Setup
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ProjectName }}-Windows-Setup
          path: ${{ env.ProjectDir}}/Deploy/OUT/*.exe
          if-no-files-found: error
          retention-days: 1
