name: Release Linux (PupNet)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PupNetVersion: "1.6.0"
  ProjectDir: "src/AvaloniaExample"
  ProjectName: "AvaloniaExample"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Print debug info
        run: dotnet --info

      # https://github.com/AppImage/AppImageKit/wiki/FUSE#install-fuse
      - name: Install FUSE
        run: sudo add-apt-repository universe && sudo apt install libfuse2

      - name: Get PupNet
        run: dotnet tool install -g KuiperZone.PupNet --version ${{ env.PupNetVersion }}

      - name: Create Archive
        working-directory: ${{ env.ProjectDir }}
        run: pupnet -y -k zip -p DefineConstants=INSTALLATION_METHOD_ARCHIVE

      - name: Create AppImage
        working-directory: ${{ env.ProjectDir }}
        run: pupnet -y -k AppImage -p DefineConstants=INSTALLATION_METHOD_APPIMAGE

      - name: Upload Archive
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ProjectName }}-Linux-Archive
          path: ${{ env.ProjectDir}}/Deploy/OUT/*.zip
          if-no-files-found: error
          retention-days: 1

      - name: Upload AppImage
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ProjectName }}-Linux-AppImage
          path: ${{ env.ProjectDir}}/Deploy/OUT/*.AppImage
          if-no-files-found: error
          retention-days: 1
